server.port=8804
spring.application.name=api-gateway

security.service.url=http://security-service:8803

resilience4j.circuitbreaker.instances.clientServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.clientServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.clientServiceCB.waitDurationInOpenState=10s

management.endpoints.web.exposure.include=health,info,metrics

spring.cloud.gateway.routes[0].id=client-service
spring.cloud.gateway.routes[0].uri=http://client-service:8805
spring.cloud.gateway.routes[0].predicates[0]=Path=/client-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1