spring.application.name=medical-history-service
server.port=8096

spring.r2dbc.url=r2dbc:postgresql://postgres:5432/clinica
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

spring.sql.init.mode=always
spring.sql.init.platform=postgres

spring.r2dbc.initialization-mode=always

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=vet-group
spring.kafka.consumer.auto-offset-reset=earliest

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${spring.application.name}