spring.application.name=security-service
#SPRING_PROFILES_ACTIVE=kafka

server.port=8803

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.bsghjumsyqxsbljsmzqb
spring.datasource.password=mAsterdog@12345_6
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.properties.hibernate.jdbc.batch_size=0
spring.jpa.properties.hibernate.order_inserts=false
spring.jpa.properties.hibernate.order_updates=false
spring.jpa.properties.hibernate.statement_cache.size=0
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.template.default-topic=auth-user-events
